version: '2'
services:
  gatling-runner:
    image: 311630568628.dkr.ecr.ap-south-1.amazonaws.com/pot7-consumer-runner:latest
    environment:
      - TOPIC_NAME=topic1-5K
      - BOOTSTRAP_SERVERS=b-10.potkafkadstcluster.tt0dxe.c2.kafka.ap-south-1.amazonaws.com:9094,b-12.potkafkadstcluster.tt0dxe.c2.kafka.ap-south-1.amazonaws.com:9094,b-6.potkafkadstcluster.tt0dxe.c2.kafka.ap-south-1.amazonaws.com:9094
      - CONSUMER_GROUP=test_group
      - POLL_WINDOW_MILLISECONDS=50
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: awslogs
      options:
        awslogs-create-group: true
        awslogs-group: /ecs/pot7-kafka-consumer
        awslogs-region: ap-south-1
        awslogs-stream-prefix: kafka-consumer