version: '2'
services:
  gatling-runner:
    # TODO insert image here
    image: 
    environment:
      - TOPIC_NAME=
      - BOOTSTRAP_SERVERS=
      - CONSUMER_GROUP=test_group
      - POLL_WINDOW_MILLISECONDS=50
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    logging:
      driver: awslogs
      options:
        awslogs-create-group: true
        awslogs-group: /ecs/pot7-kafka-consumer
        # TODO should be parametrized
        #awslogs-region: us-east-1
        awslogs-region: ap-south-1
        awslogs-stream-prefix: kafka-consumer
